export const BOOKS_FETCH_REQUEST = 'BOOKS_FETCH_REQUEST';
export const BOOKS_FETCH_SUCCESS = 'BOOKS_FETCH_SUCCESS';
export const BOOKS_FETCH_FAILURE = 'BOOKS_FETCH_FAILURE';

export const USERS_FETCH_REQUEST = 'USERS_FETCH_REQUEST';
export const USERS_FETCH_SUCCESS = 'USERS_FETCH_SUCCESS';
export const USERS_FETCH_FAILURE = 'USERS_FETCH_FAILURE';

export const CHECK_OUTS_FETCH_REQUEST = 'CHECK_OUTS_FETCH_REQUEST';
export const CHECK_OUTS_FETCH_SUCCESS = 'CHECK_OUTS_FETCH_SUCCESS';
export const CHECK_OUTS_FETCH_FAILURE = 'CHECK_OUTS_FETCH_FAILURE';

export const CHECK_OUT_REQUEST = 'CHECK_OUT_REQUEST';
export const CHECK_OUT_SUCCESS = 'CHECK_OUT_SUCCESS';
export const CHECK_OUT_FAILURE = 'CHECK_OUT_FAILURE';

export const SELECT_USER = 'SELECT_USER';
